### ISSUE TITLE
Problem installing Go releaser in Travis

### ISSUE THREAD

**Issue by bobvanluijt** [goreleaser/goreleaser#588] opened 2018-03-01 15:43 UTC
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

### Description

When installing go releaser directly in Travis-ci (go 1.9) it recently started to return the following error:

```
$ go get github.com/goreleaser/goreleaser
# github.com/goreleaser/nfpm/deb
../../goreleaser/nfpm/deb/deb.go:132:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:191:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:215:10: unknown field 'Format' in struct literal of type tar.Header
```

### Environment

Please paste the output of:

`go version go1.9 linux/amd64`

### Steps to Reproduce

https://travis-ci.org/creativesoftwarefdn/weaviate/jobs/347816755

**Comment by caarlos0** [comment] 2018-03-01 16:10
Hey @bobvanluijt , this seems a dupe of  #585

Please use the binary release as per [docs](https://goreleaser.com/#continuous_integration.travis):

```sh
curl -sL http://git.io/goreleaser | bash
```

Let me know how it work out, cheers!

**Closed** 2018-03-01 16:11 UTC

**Comment by bobvanluijt** [comment] 2018-03-01 17:08
Jep, that's it. Thanks mate
