### ISSUE TITLE
snapcraft publish cause panic

### ISSUE THREAD

**Issue by guumaster** [goreleaser/goreleaser#1409] opened 2020-03-31 08:36 UTC
**Describe the bug**

I've setup `goreleaser` as github action to publish my binary in different forms. It's failing with panic on the  snap publication. 

**To Reproduce**

It happens when I set `snapcrafts[0].publish: true`. Then the Github Action fails. It can generates the snap and all other builds, but panic at some point. (see logs at the end).

```
//.goreleaser.yml
//...

snapcrafts:
  - id: hostctl
    name: hostctl
    summary: manage your hosts file like a pro
    description: manage your hosts file like a pro.
    grade: stable
    confinement: strict
    license: MIT
    publish: true
    apps:
      hostctl:
        plugs: ["network-control"]
    plugs:
      network-control:
        read:
          - /etc/hosts
        write:
          - /etc/hosts

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

The expected behavior is to publish to snap store and not fail if the package is pending review.

**Environment (please complete the following information):**

It fails on Github Action run.

**Additional context**

``` 
2020-03-31T07:57:45.5064943Z     snapcraft packages       
2020-03-31T07:57:45.5074133Z        creating                  arch=amd64 snap=dist/hostctl_0.5.5_linux_amd64.snap
2020-03-31T07:57:46.7736011Z     calculating checksums    
2020-03-31T07:57:46.7737310Z        checksumming              file=hostctl_0.5.5_linux_amd64.deb
2020-03-31T07:57:46.7739875Z        checksumming              file=hostctl_0.5.5_linux_64-bit.tar.gz
2020-03-31T07:57:46.7740854Z        checksumming              file=hostctl_0.5.5_macOS_64-bit.tar.gz
2020-03-31T07:57:46.7746695Z        checksumming              file=hostctl_0.5.5_windows_64-bit.zip
2020-03-31T07:57:46.7810059Z     signing artifacts        

....

2020-03-31T07:57:46.7820618Z        docker images            
2020-03-31T07:57:46.7821189Z        snapcraft packages       
2020-03-31T07:57:46.7821871Z           pushing snap              snap=hostctl_0.5.5_linux_amd64.snap
2020-03-31T07:57:58.5089531Z           Waiting for previous upload(s) to complete their review process. snap=hostctl_0.5.5_linux_amd64.snap
2020-03-31T07:57:58.5090999Z        github/gitlab/gitea releases
2020-03-31T07:57:58.5092066Z           token type                type=github

....

2020-03-31T07:57:59.5987854Z 
2020-03-31T07:57:59.6022751Z panic: runtime error: invalid memory address or nil pointer dereference
2020-03-31T07:57:59.6023596Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf3e8ce]
2020-03-31T07:57:59.6024253Z 
2020-03-31T07:57:59.6024808Z goroutine 1 [running]:
2020-03-31T07:57:59.6025825Z github.com/kamilsk/retry/v4.(*result).Error(0xc00042cc00, 0x4, 0x4)
2020-03-31T07:57:59.6026530Z 	<autogenerated>:1 +0x2e
2020-03-31T07:57:59.6027188Z github.com/pkg/errors.(*withMessage).Error(0xc00042cc20, 0x0, 0x0)
2020-03-31T07:57:59.6027976Z 	/Users/carlos/Code/Go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
2020-03-31T07:57:59.6028752Z github.com/pkg/errors.(*withMessage).Error(0xc00044ade0, 0x0, 0x0)
2020-03-31T07:57:59.6029543Z 	/Users/carlos/Code/Go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
2020-03-31T07:57:59.6030351Z github.com/apex/log.(*Entry).WithError(0xc0003b9ba0, 0x159e220, 0xc00044ae20, 0x0)
2020-03-31T07:57:59.6031161Z 	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/entry.go:55 +0x49
2020-03-31T07:57:59.6032030Z github.com/apex/log.(*Logger).WithError(0x1e4dbe0, 0x159e220, 0xc00044ae20, 0x0)
2020-03-31T07:57:59.6032706Z 	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/logger.go:79 +0x9f
2020-03-31T07:57:59.6033294Z github.com/apex/log.WithError(...)
2020-03-31T07:57:59.6033872Z 	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/pkg.go:43
2020-03-31T07:57:59.6034594Z main.main()
2020-03-31T07:57:59.6035219Z 	/Users/carlos/Code/goreleaser/goreleaser/main.go:116 +0x1c76
2020-03-31T07:57:59.6058512Z ##[error]The process '/home/runner/work/_temp/9db30097-4d90-4d48-897a-1bee00ef71c3/goreleaser' failed with exit code 2
```

**Comment by caarlos0** [comment] 2020-03-31 13:23
duplicate of #1410

sorry for the issue

fix incoming

**Closed by caarlos0** 2020-03-31 13:23 UTC
Labels: bug
