### ISSUE TITLE
[Bug]: Goreleaser silently for invalid credentials on S3 uploads

### ISSUE THREAD

**Issue by rnikoopour** [goreleaser/goreleaser#2652] opened 2021-11-09 21:16 UTC
### What happened?

When doing a release with S3 my credentials were not set properly.  goreleaser ran to completion and did not raise any errors that the S3 uploads fail.

### How can we reproduce this?

1. Create a .goreleaser.yml that uploads to an S3 bucket.
2. Remove credentials that give write access to that bucket
3. Run goreleaser

This should run to completion without alerting that the S3 uploads failed.

### goreleaser version

```bash
goreleaser version 0.183.0
commit: be6199f08167cc85b0b16cefc02d8106237853b1
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2021-11-12 03:46
if someone wants to take a look at this, please feel free to do so :)

**Comment by dirien** [comment] 2021-11-15 10:52
@caarlos0, I will do. if its okay?

**Comment by caarlos0** [comment] 2021-11-15 13:49
sure, go ahead @dirien

**Comment by dirien** [comment] 2021-11-15 18:39
Hi @rnikoopour,

i try to recreate your scenario, but i can't recreate it to see the same as you:

What did i do:

1. Create an AWS S3 (Question 1: Are you using aws s3 or an s3 compatible storage?)
1. Postivie Test with full access (r+w)
![image](https://user-images.githubusercontent.com/38325136/141836286-b5694fb5-1336-4933-8700-7e797d8634c4.png)
1. Remove Write Access
``` 
⨯ release failed after 12.53s error=blobs: failed to publish artifacts: failed to write to bucket: blob (key "minectl/v0.12.0/minectl_0.12.0_linux_amd64.tar.gz") (code=Unknown): AccessDenied: Access Denied
```

Do you have some more input about your settings?

**Comment by rnikoopour** [comment] 2021-11-15 22:56
> Question 1: Are you using aws s3 or an s3 compatible storage?

I was using AWS S3.

> Do you have some more input about your settings?
What more information do you need regarding the settings?    

Off the top of my head I don't really have more information.  I never removed write access for the credentials that were being used.  I may have had expired AWS credentials in my `~/.aws/credentials` but I didn't have a profile set when I tried to upload and it failed silently. 

My colleague was able to reproduce the error on his machine.  During one of our last releases it silently failed.  He was in the same situation with either expired credentials in `~/.aws/credentials` with no profile set.

> Remove Write Access
How did you remove the write access?  In my scenario I never removed any explicit permissions.  I just didn't have a valid AWS Profile set and the creds stored in `~/.aws/credentials` were expired.

**Comment by dirien** [comment] 2021-11-16 07:37
hi @rnikoopour,

that will be helpful. Currently i test with setting the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID but try to rebuild your scenario!

Thanks

**Comment by dirien** [comment] 2021-11-16 20:15
hi @rnikoopour, i tried it with temp. credentials via aws cli 

`aws sts assume-role --duration-seconds 900 --role-arn arn:aws:iam::343319427887:role/s3 --role-session-name "RoleSession1"`

```
{
    "Credentials": {
        "AccessKeyId": "zzz",
        "SecretAccessKey": "yyy",
        "SessionToken": "xxx",
        "Expiration": "2021-11-16T19:11:38+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "AROAU733OXMX2JF3UZEWZ:RoleSession1",
        "Arn": "arn:aws:sts::343319427887:assumed-role/s3/RoleSession1"
    }
}

```

And i get the feedback: 

`⨯ release failed after 13.74s error=blobs: failed to publish artifacts: failed to write to bucket: blob (key "minectl/v0.12.0/minectl_0.12.0_linux_amd64.tar.gz") (code=Unknown): ExpiredToken: The provided token has expired.`

I have no other idea on how to test this. @rnikoopour maybe you can create a screenshot

**Comment by dorner** [comment] 2021-11-16 21:28
I'm seeing the same issue. My output looks slightly different, but same overall problem - no errors are reported.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/1986893/142055866-a8b5069e-a946-495a-975b-4af2d83280e9.png">

**Comment by rnikoopour** [comment] 2021-11-16 22:00
@dirien thanks for digging into this and trying to repro.  The photo from @dorner is the same output I had.

**Comment by dirien** [comment] 2021-11-16 23:39
@dorner and @rnikoopour are you using some kind of oidc to provide the credentials?

@dorner: can you explain your setup? are you using the aws cli for auth? That would help me much to reconstruct the issue to find a solution.

**Comment by dorner** [comment] 2021-11-17 14:18
@dirien nope, just plain environment variables. In this case it turns out the variables were set to empty strings but I had no idea.

**Comment by dorner** [comment] 2021-11-17 14:18
This is running on GitHub Actions by the way.

**Comment by dorner** [comment] 2021-11-17 14:42
hmm... something else is weird here. When I replace the GoReleaser code with a straight `aws s3 cp` command line call, it uploads fine. But GoReleaser shows the "publishing" line and nothing else.

Also, with debug logs off the blobs show nothing at all in the publishing section.

**Comment by dirien** [comment] 2021-11-17 17:45
So I tested every scenarion, and I get all the time a correct error message. I could not trigger a scenario, where the underlying library did not come up with an error message.

Maybe it helps understand, that goreleaser uses 

```
... following order:

- Environment variables.
- Shared credentials file.
- If your application is running on an Amazon EC2 instance, IAM role for Amazon EC2.
```

https://goreleaser.com/customization/blob/#s3-provider

different locations for the credentials. In your case @dorner it could be still that the .aws/credentials are present. 

FYI maybe @caarlos0 has some ideas. I found this so strange and I am so sorry to not able to reproduce it.

**Comment by dorner** [comment] 2021-11-17 17:48
Hmm... but in this case, the env variables *are* there and I'm still not seeing the blobs being published correctly. So there's some disconnect between how the AWS command line library reads them and how GoReleaser reads them. :(

**Comment by caarlos0** [comment] 2021-11-17 17:59
GoRelaser uses https://github.com/google/go-cloud 

I see no relevant issues there regarding s3... maybe you can try to build a reproducible using your problematic keys in a main.go using them?

Something like:

```go
package main

import (
	"context"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/s3blob"
)


func main() {
	// blob.OpenBucket creates a *blob.Bucket from a URL.
	bucket, err := blob.OpenBucket(ctx, "s3://my-bucket?region=us-west-1")
	if err != nil {
		return err
	}
	defer bucket.Close()
	
	w, err := bucket.NewWriter(ctx, "foo.txt", nil)
	if err != nil {
		return err
	}
	_, writeErr := fmt.Fprintln(w, "Hello, World!")
	// Always check the return value of Close when writing.
	closeErr := w.Close()
	if writeErr != nil {
		log.Fatal(writeErr)
	}
	if closeErr != nil {
		log.Fatal(closeErr)
	}
}
```

(straight copied from their help page)

Then we can see if its something there, something on goreleaser, or something else entirely...

**Comment by dirien** [comment] 2021-11-17 18:22
i like this idea @caarlos0!

**Comment by dirien** [comment] 2021-12-03 18:12
Should we close this issue? Or what I can offer is, to do a Teams/Webex/Slack session to see the error live in action :) Most of the time this helps me to gather more infos. C'mon, what works and work should work in OSS too? 😛

**Comment by dorner** [comment] 2021-12-03 18:14
I actually gave up on GoReleaser and am using the AWS command line right now. The pipeline is working. Moving it back is a bit risky at this point. I might have another path to test this in a week or two.

**Comment by caarlos0** [comment] 2022-02-05 21:03
@dorner did you test it again by any chance?

**Comment by dorner** [comment] 2022-02-06 19:35
Unfortunately not. I have something that works now and I don't even have the write access to test this again right now. :(

**Comment by caarlos0** [comment] 2022-02-07 00:43
ok, no problem @dorner 

since we weren't able to reproduce, and no one else stepped up with the same issue, will close this for now.

Thanks for the issue anyway 🙏

**Comment by remyleone** [comment] 2022-03-16 15:49
I got the issue with a non-AWS s3. Did somebody successfully make goreleaser work with a non-aws s3?

**Comment by caarlos0** [comment] 2022-03-16 17:11
the goreleaser s3 tests run agains a minio, so it should work...

**Comment by caarlos0** [comment] 2022-06-21 16:46
@sandromello what appears in the logs when you dont have the creds mapped?

**Comment by sandromello** [comment] 2022-06-21 18:32
@caarlos0 the logs doesn't show any errors, but the release isn't uploaded to the S3. I tried to simulate locally with the same credentials and it worked. I've used the same version on github actions and locally (1.9.2).

**Comment by sandromello** [comment] 2022-06-22 15:39
@caarlos0 indeed you were right, I've tested with empty credentials and did not returned any error. I've tested with the snippet (did some small changes) that you provide and the errors appears:
```
2022/06/22 12:30:10 blob (key "path/to/file.txt") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

The error returns when closing the `*blob.Writer`.
Maybe it could be [this piece of code](https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/blob/upload.go#L236-L237) which I think is inverted (it should match an error not nil)

**Comment by caarlos0** [comment] 2022-06-22 17:09
ah, I think that should probably be 

```go
if cerr := w.Close(); cerr != nil {
````

good catch, thanks for help testing, will reopen this one!

anyone that wants to pr this change, feel free to do so :)

**Closed** 2022-06-24 03:14 UTC
Labels: bug
