### ISSUE TITLE
build command ignores --single-target

### ISSUE THREAD

**Issue by nwneisen** [goreleaser/goreleaser#4412] opened 2023-11-07 21:45 UTC
### What happened?

**What happened**
I'm wanting to only build one target that doesn't get published. To do this, I'm using the following

```
GOOS=linux GOARCH=amd64 goreleaser build --clean --snapshot --single-target
```

My understanding is that this should clean out the dist folder and then build a single binary for linux amd64 without using a git tag. Instead, it's still building a binary for all platforms

```
  • starting build...
  • loading                                          path=.goreleaser.yaml
  • building only for linux/amd64                    reason=single target is enabled
  • skipping validate...
  • loading environment variables
  • getting and validating git state
    • ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
    • git state                                      commit=d4b5de7509de37b868a8051e090fed22e5d1cbcf branch=CI current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=0.0.0-d4b5de7
  • checking distribution directory
    • cleaning dist
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/windows_386/binary.exe
    • building                                       binary=dist/linux_amd64_v1/binary
    • building                                       binary=dist/linux_386/binary
    • building                                       binary=dist/linux_arm64/binary
    • building                                       binary=dist/darwin_amd64_v1/binary
    • building                                       binary=dist/darwin_arm64/binary
    • building                                       binary=dist/windows_arm64/binary.exe
    • building                                       binary=dist/windows_amd64_v1/binary.exe
```

**What I expected to happen**
Only the binary for linux amd64 should've been built

### How can we reproduce this?

I'm running ubuntu 22.04 and using goreleaser from snap. I use the following command

```
GOOS=linux GOARCH=amd64 goreleaser build --clean --snapshot --single-target
```

Ultimately, this will be running an ubuntu 22.04 image in CI which downloads goreleaser as part of a goreleaser action. I'm getting the same behavior in CI.

### goreleaser version

```bash
1.22.0

I just checked in CI and 1.21.2 works as expected
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2023-11-08 01:02
can you check on `main`? I think this was fixed in #4411

**Comment by caarlos0** [comment] 2023-11-08 01:03
if it doesn't work there, please share a reproducible... I'm unable to reproduce this on `main`.

**Comment by nwneisen** [comment] 2023-11-08 01:19
It still does it with main
```
$ ../goreleaser/goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    devel
GitCommit:     c0b2be344fca8c66fda35391ca76d9c3ca9753c8
GitTreeState:  clean
BuildDate:     2023-11-07T11:40:31
BuiltBy:       unknown
GoVersion:     go1.21.3
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
$ GOOS=linux GOARCH=amd64 ../goreleaser/goreleaser build --clean --snapshot --single-target
  • starting build...
  • loading                                          path=.goreleaser.yaml
  • building only for linux/amd64                    reason=single target is enabled
  • skipping validate...
  • loading environment variables
  • getting and validating git state
    • ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
    • git state                                      commit=79c784d9e1a2c1ea6d3a4fc3a23857bf9966c4ff branch=BOP-50-CI-on-merge current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=bctl-0.0.0-79c784d
  • checking distribution directory
    • cleaning dist
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/windows_386/binary.exe
    • building                                       binary=dist/windows_amd64_v1/binary.exe
    • building                                       binary=dist/darwin_amd64_v1/binary
    • building                                       binary=dist/linux_386/binary
    • building                                       binary=dist/darwin_arm64/binary
    • building                                       binary=dist/linux_amd64_v1/binary
    • building                                       binary=dist/linux_arm64/binary
    • building                                       binary=dist/windows_arm64/binary.exe
    • took: 3s
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • build succeeded after 3s
  • thanks for using goreleaser!
```

**Comment by caarlos0** [comment] 2023-11-08 01:36
@nwneisen can you share a reproducible?

**Comment by caarlos0** [comment] 2023-11-08 02:03
found it, its not matching any build config, which is then causing it to build with defaults.

fixed.

**Comment by caarlos0** [comment] 2023-11-08 02:03
thanks for the report!

**Closed** 2023-11-08 02:03 UTC
Labels: bug, triage

**Comment by nwneisen** [comment] 2023-11-08 03:12
Thanks for the quick fix!
