### ISSUE TITLE
[Bug]: error uploading artifacts to github releases

### ISSUE THREAD

**Issue by chetan** [goreleaser/goreleaser#2746] opened 2021-12-07 19:53 UTC
### What happened?

Artifacts sometimes fail to upload, due to github API failures.

This is similar to the issue reported in #2506. AFAICT, it's an issue on github's end. Here's a larger log of output from my build running in a github action:

```text

• uploading to release      file=dist/checksums.txt name=checksums.txt
• failed to upload artifact, will retry artifact=checksums.txt error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=checksums.txt: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/checksums.txt name=checksums.txt
• failed to upload artifact, will retry artifact=checksums.txt error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=checksums.txt: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=2

• uploading to release      file=dist/traefik-kop_0.8.1_Linux_arm64.tar.gz name=traefik-kop_0.8.1_Linux_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_arm64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_arm64.tar.gz: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_arm64.tar.gz name=traefik-kop_0.8.1_Linux_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_arm64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=2

• uploading to release      file=dist/traefik-kop_0.8.1_Linux_x86_64.tar.gz name=traefik-kop_0.8.1_Linux_x86_64.tar.gz

• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv6.tar.gz name=traefik-kop_0.8.1_Linux_armv6.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv6.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv6.tar.gz: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv6.tar.gz name=traefik-kop_0.8.1_Linux_armv6.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv6.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv6.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 11; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=2
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv6.tar.gz name=traefik-kop_0.8.1_Linux_armv6.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv6.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv6.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 13; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=3
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv6.tar.gz name=traefik-kop_0.8.1_Linux_armv6.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv6.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv6.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=4

• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_arm64.tar.gz name=traefik-kop_0.8.1_Darwin_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_arm64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_arm64.tar.gz: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_arm64.tar.gz name=traefik-kop_0.8.1_Darwin_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_arm64.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_arm64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 25; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=2
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_arm64.tar.gz name=traefik-kop_0.8.1_Darwin_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_arm64.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_arm64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 29; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=3
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_arm64.tar.gz name=traefik-kop_0.8.1_Darwin_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_arm64.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_arm64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 33; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=4
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_arm64.tar.gz name=traefik-kop_0.8.1_Darwin_arm64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_arm64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=5

• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv7.tar.gz name=traefik-kop_0.8.1_Linux_armv7.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv7.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv7.tar.gz: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv7.tar.gz name=traefik-kop_0.8.1_Linux_armv7.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv7.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv7.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 23; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=2
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv7.tar.gz name=traefik-kop_0.8.1_Linux_armv7.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv7.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv7.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 27; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=3
• uploading to release      file=dist/traefik-kop_0.8.1_Linux_armv7.tar.gz name=traefik-kop_0.8.1_Linux_armv7.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Linux_armv7.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Linux_armv7.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=4

• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_x86_64.tar.gz name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_x86_64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz: 502 Error uploading to https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be: 500 [] try=1
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_x86_64.tar.gz name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_x86_64.tar.gz error=Post "https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 39; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error try=2
• uploading to release      file=dist/traefik-kop_0.8.1_Darwin_x86_64.tar.gz name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz
• failed to upload artifact, will retry artifact=traefik-kop_0.8.1_Darwin_x86_64.tar.gz error=POST https://uploads.github.com/repos/jittering/traefik-kop/releases/54810593/assets?name=traefik-kop_0.8.1_Darwin_x86_64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=3
```

I cleaned up and sorted the output so its easier to read. It seems that in each case, a `5xx` error is followed by `422` on each successive retry. In this scenario, it might be necessary to check the list of release assets and/or delete it before retrying. 

In my case, it took my several rebuilds (5 tries) with manually deleting the release in between until I was able to get a clean build where every artifact uploaded properly. 

### How can we reproduce this?

Seems to be a github issue, not sure there will be an easy way to reproduce

### goreleaser version

```bash
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxmcd** [comment] 2021-12-09 01:49
I've been getting this error today as well: https://github.com/maxmcd/bramble/runs/4465299050?check_suite_focus=true

**Comment by jlucktay** [comment] 2021-12-11 04:21
Same here: https://github.com/jlucktay/stack/runs/4491068251?check_suite_focus=true

**Comment by avelino** [comment] 2021-12-28 11:56
I am having the same problem at [prestd](https://github.com/prest/prest)
https://github.com/prest/prest/runs/4649770692?check_suite_focus=true#step:15:426

**Comment by caarlos0** [comment] 2021-12-28 12:01
> [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]

when this happens, it usually means that goreleaser ran multiple times against the same tag, as the files are already there...

we should probably drop the retries in this case though

**Comment by caarlos0** [comment] 2021-12-28 12:30
hmm, seems to be this https://github.com/google/go-github/issues/2113

**Comment by avelino** [comment] 2021-12-28 13:01
> when this happens, it usually means that goreleaser ran multiple times against the same tag, as the files are already there...


If the file already exists and you are generating a "new" release, shouldn't you overwrite it?

Thinking that you are consuming an upload api you should delete the existing file and upload it again

**Comment by caarlos0** [comment] 2021-12-28 14:15
> If the file already exists and you are generating a "new" release, shouldn't you overwrite it?

too destructive, rather not... who knows why the file already exists... it may not even have been created by goreleaser

**Comment by avelino** [comment] 2021-12-29 08:32
@caarlos0 if we put a parameter to force (aka `--force`) the replacement of the file?

in my case that solves it, all builds are (and will be) generated _"automatically"_ via pipeline (github actions), if there is one, it was because of some error in the middle of the process, it's ok to overwrite.

**Comment by caarlos0** [comment] 2022-01-07 01:36
> @caarlos0 if we put a parameter to force (aka `--force`) the replacement of the file?

I don't like the idea... 

* if its a flag, it would require the user to either change their CI config and retag (which is not good) or run from their machines instead of CI (also not that good)
* if its a config, to be safe, they would have to always have that set there... which would still lead to retag if its not there beforehand, or to accidental destruction actions if it is always there...

to me it seems the right thing is to fix this on go-github

**Comment by chetan** [comment] 2022-01-09 15:15
@caarlos0 Is there a way to re-release a specific tag? In my case, when I ran into this issue, I had to manually delete the release from github and then run goreleaser again. 

> > [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
> 
> when this happens, it usually means that goreleaser ran multiple times against the same tag, as the files are already there...

goreleaser already fails-fast when a release already exists, so if it's gotten to the point of uploading artifacts, it means that the release was created during the current run. If that's the case, I don't see any reason why the file can't simply be deleted and retried automatically. 

As you can see from my original problem report, the `already_exists` error only returns after the initial `522` error. My guess is that despite github throwing 522 on the initial upload, the asset object is actually getting created and stored, but an error was thrown at some other point in the process. Thus, any subsequent retries hit the `already_exists` error. Obviously the core issue is at github's end, but it can be worked around by simply cleaning up and retrying, possibly with some appropriate exponential backoff between each try.

**Comment by caarlos0** [comment] 2022-01-10 00:50
> goreleaser already fails-fast when a release already exists

it does not...

**Comment by chetan** [comment] 2022-01-10 15:19
Sorry, you're right, I'm misremembering the sequence from when I was troubleshooting and don't have those logs any more. I just re-ran a release for an existing tag manually and I see this message:

```text
      • scm releases
         • creating or updating release repo=jittering/traefik-kop tag=v0.9.1
```

All of the artifact uploads indeed fail immediately (only 422 errors, no 5xx) as they already exist. I think in this case, I agree with what @avelino said above -- if it's a new release, overwrite the file; if updating, do not retry a `422 already_exists`, just skip or fail the process. 

Unless there is some race condition with multiple releases happening simultaneously, I don't see why this wouldn't be a safe option. For extra caution, a flag which users can decide to always include in their build should be a good compromise. 

I don't think the linked go-github error linked above is relevant here as that appears to be some internal problem while the `502` here is come backing from github's API. This https://github.com/google/go-github/issues/304 issue does mention 502s on upload and the response was (rightly) that it should be handled by the client.

**Comment by caarlos0** [comment] 2022-01-10 16:36
> Unless there is some race condition with multiple releases happening simultaneously, I don't see why this wouldn't be a safe option. For extra caution, a flag which users can decide to always include in their build should be a good compromise.

this happens more often than not, people setup goreleaser on commit to main AND tag, and get concurrent releases... if we allow to override, who knows what the end release will look like

the issue seems to be within go-github https://github.com/google/go-github/issues/2113

**Comment by caarlos0** [comment] 2022-02-05 20:57
is this still happening?

**Comment by avelino** [comment] 2022-02-05 21:07
> 

No reply, I had no more problem (after I reported, ANY more releases were generated using goreleaser)

**Comment by caarlos0** [comment] 2022-02-05 21:13
ok, will close this then

thanks all!

**Closed by caarlos0** 2022-02-05 21:13 UTC
Labels: bug

**Comment by vandot** [comment] 2022-04-19 15:57
@caarlos0 it started happening to me from yesterday [here](https://github.com/ethersphere/bee-clef/runs/6080768209?check_suite_focus=true#step:7:180) is this fixed in some newer versions of `goreleaser`?
I am using `troian/golang-cross` didn't had time to migrate it to new setup.

**Comment by caarlos0** [comment] 2022-04-19 18:05
This is an issue on github api, happens from time time to time to some people in some places in some repos, nothing I can do about it.

Best thing is open a support ticket for them to make some noise.

I also opened this discussion a while back: https://github.com/github/feedback/discussions/14341

**Comment by rfay** [comment] 2022-06-11 22:12
Shoot, I was hoping that goreleaser would have a workaround for this problem at github. I've seen it so very many times-  * https://github.com/skx/github-action-publish-binaries/issues/33

The problem is that when you're doing a release and it fails the recovery is tremendously awkward, can result in deleting the release or at least the stuff already uploaded to the release so you can start over again. But from what I hear there's no workaround in goreleaser, right?

**Comment by caarlos0** [comment] 2022-06-12 01:16
> But from what I hear there's no workaround in goreleaser, right?

correct - see https://github.com/goreleaser/goreleaser/issues/2746#issuecomment-1009079939
