### ISSUE TITLE
Add support for Gitlab release

### ISSUE THREAD

**Issue by diegobernardes** [goreleaser/goreleaser#689] opened 2018-06-03 23:17 UTC
**Is your feature request related to a problem? Please describe.**
As microsoft has planned or already bought Github, we need a alternative, the goto may be Gitlab.

**Describe the solution you'd like**
The really same thing the Github provider does, but for Gitlab.

**Comment by caarlos0** [comment] 2018-06-04 11:44
duplicate of #110

**Closed by caarlos0** 2018-06-04 11:44 UTC
