### ISSUE TITLE
homebrew causing panic

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#1408] opened 2020-03-31 03:05 UTC
Running

goreleaser --rm-dist

**To Reproduce**
https://github.com/blacktop/ipsw/blob/master/.goreleaser.yml

> Make sure your config file is valid by running
   • config is valid
**Environment:**

- OS: mac
- OS version: latest
- GoReleaser Version 
version: 0.130.0
commit: fa608c302efac346ea198f193a5d284bafa63fce
built by: homebrew
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1b4205e]

goroutine 1 [running]:
github.com/kamilsk/retry/v4.(*result).Error(0xc0001d44e0, 0x8, 0x8)
	<autogenerated>:1 +0x2e
github.com/pkg/errors.(*withMessage).Error(0xc0001d4540, 0x0, 0x0)
	/private/tmp/goreleaser-20200329-38787-1aaywai/.brew_home/go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
github.com/pkg/errors.(*withMessage).Error(0xc00047e880, 0x0, 0x0)
	/private/tmp/goreleaser-20200329-38787-1aaywai/.brew_home/go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
github.com/apex/log.(*Entry).WithError(0xc000593ba0, 0x21a3aa0, 0xc00047e900, 0x0)
	/private/tmp/goreleaser-20200329-38787-1aaywai/.brew_home/go/pkg/mod/github.com/apex/log@v1.1.1/entry.go:55 +0x49
github.com/apex/log.(*Logger).WithError(0x2a640a0, 0x21a3aa0, 0xc00047e900, 0x0)
	/private/tmp/goreleaser-20200329-38787-1aaywai/.brew_home/go/pkg/mod/github.com/apex/log@v1.1.1/logger.go:79 +0x9f
github.com/apex/log.WithError(...)
	/private/tmp/goreleaser-20200329-38787-1aaywai/.brew_home/go/pkg/mod/github.com/apex/log@v1.1.1/pkg.go:43
main.main()
	/private/tmp/goreleaser-20200329-38787-1aaywai/main.go:116 +0x1c76
make: *** [release] Error 2
```

**Comment by bdwyertech** [comment] 2020-03-31 03:08
Seeing same... Rolling back to v0.129.0 did the trick for me.

**Comment by AeroNotix** [comment] 2020-03-31 09:22
Same here - had to tag to v0.129.0 in order to not end up with the stacktrace in the OP.

**Comment by caarlos0** [comment] 2020-03-31 13:22
duplicate of #1410

sorry for the issue btw :/

**Closed by caarlos0** 2020-03-31 13:22 UTC
Labels: bug
