### ISSUE TITLE
Homebrew release is coupled with github release

### ISSUE THREAD

**Issue by combor** [goreleaser/goreleaser#1237] opened 2019-11-09 09:39 UTC
Hi guys,

Do I understand this correctly that if the github release is disabled than homebrew tap is not gonna be pushed also?

https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/brew/brew.go#L169

We have another switch to controll if the homebrew tap is pushed there: https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/brew/brew.go#L162

So maybe the github release and homebrew tap shouldn't be coupled?

My use case is that I'm not releasing to github but would like to push the tap only.

**Comment by caarlos0** [comment] 2019-11-15 13:54
the homebrew tap needs a release to somewhere (github or gitlab) to work, because it uses those urls to download the artifacts.

that's why one depends on the other.

right now I don't have planned on adding support to other "backends". 

That being said, closing this :)

**Comment by combor** [comment] 2019-11-17 15:09
But I don't need it to publish anywhere, I just need it to generate the brew tap only, this was definitely possible several releases back and was changed in this commit: https://github.com/goreleaser/goreleaser/commit/2da118a296a0dd8cb5d9c591abbaad845b15c900. It stopped working when I updated goreleasrer.

**Comment by caarlos0** [comment] 2019-11-17 20:55
understood, makes sense, definitely a bug then

thanks for reporting :)

**Comment by caarlos0** [comment] 2019-11-20 01:39
@combor please check #1252 :)

**Comment by lumaxis** [comment] 2020-04-04 01:44
@caarlos0 Unfortunately, I think this was broken again by #1374 😕

**Comment by caarlos0** [comment] 2020-04-05 00:05
hey @lumaxis, do you have a reproducible so I can take a look?

**Comment by lumaxis** [comment] 2020-04-05 14:54
Sure!

1. Clone https://github.com/cli/cli
2. Run `goreleaser release --snapshot` or `goreleaser release --np-publish`
3. Observe that no Homebrew Formula is produced in `dist/`

**Comment by caarlos0** [comment] 2020-04-06 12:37
will take a look, thanks @lumaxis 🙏

**Comment by caarlos0** [comment] 2020-04-07 01:16
check https://github.com/goreleaser/goreleaser/pull/1425

**Comment by lumaxis** [comment] 2020-04-07 10:49
Nice! Looks good from what I can tell.
And thanks for the quick fix 🙂

**Closed** 2020-04-09 13:28 UTC
Labels: question
