### ISSUE TITLE
[Bug]: go install failed

### ISSUE THREAD

**Issue by sixg0000d** [goreleaser/goreleaser#2463] opened 2021-09-06 15:17 UTC
### What happened?

I want to install goreleaser by go install and I did running `go install github.com/goreleaser/goreleaser@latest` as from document, but it is interrupted and return info:
```
go/pkg/mod/github.com/goreleaser/goreleaser@v0.177.0/internal/pipe/reddit/reddit.go:11:2: reading github.com/vartanbeno/go-reddit/go.mod at revision v2.0.1: unknown revision v2.0.1
```

It seems [vartanbeno/go-reddit](https://github.com/vartanbeno/go-reddit/) revoked v2.0.1 from [tags](https://github.com/vartanbeno/go-reddit/tags)

### How can we reproduce this?

`go install github.com/goreleaser/goreleaser@latest`

### goreleaser version

```bash
It's not installed yet.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developer-guy** [comment] 2021-09-06 16:30
hello @sixg0000d, thanks for opening an issue but I couldn't reproduce the same issue, everything is working fine for me. I did the following steps to reproduce the issue:
```shell
$ go clean --modcache

$ sudo rm -rf $GOPATH/pkg/mod/github.com/vartanbeno/

$ go install github.com/goreleaser/goreleaser@latest

$ goreleaser -version
goreleaser version dev
module version: v0.177.0, checksum: h1:pPjL2NGfrLY5mqEK+3Nk6IgZtPyU9zB9mFxKeF3MU8w=
https://goreleaser.com

$ go list -m -versions github.com/vartanbeno/go-reddit/v2
github.com/vartanbeno/go-reddit/v2 v2.0.0 v2.0.1
```

![Screen Shot 2021-09-06 at 19 29 50](https://user-images.githubusercontent.com/16693043/132244964-9bf88b05-ccd6-4daf-a414-13eb47f684c5.png)


PTAL @caarlos0 @Dentrax @erkanzileli

**Comment by Dentrax** [comment] 2021-09-06 16:51
```dockerfile
FROM golang:1.17.0-alpine
RUN go install github.com/goreleaser/goreleaser@latest
```

This works too. But this not:

```bash
$ cd /path/to/goreleaser
$ go mod graph
go: github.com/vartanbeno/go-reddit/v2@v2.0.1: reading github.com/vartanbeno/go-reddit/go.mod at revision v2.0.1: unknown revision v2.0.1
```

**Comment by sixg0000d** [comment] 2021-09-06 17:21
> hello @sixg0000d, thanks for opening an issue but I couldn't reproduce the same issue, everything is working fine for me. I did the following steps to reproduce the issue:
> 
> ```shell
> $ go clean --modcache
> 
> $ sudo rm -rf $GOPATH/pkg/mod/github.com/vartanbeno/
> 
> $ go install github.com/goreleaser/goreleaser@latest
> 
> $ goreleaser -version
> goreleaser version dev
> module version: v0.177.0, checksum: h1:pPjL2NGfrLY5mqEK+3Nk6IgZtPyU9zB9mFxKeF3MU8w=
> https://goreleaser.com
> 
> $ go list -m -versions github.com/vartanbeno/go-reddit/v2
> github.com/vartanbeno/go-reddit/v2 v2.0.0 v2.0.1
> ```
> 
> ![Screen Shot 2021-09-06 at 19 29 50](https://user-images.githubusercontent.com/16693043/132244964-9bf88b05-ccd6-4daf-a414-13eb47f684c5.png)
> 
> PTAL @caarlos0 @Dentrax @erkanzileli

Sorry for lost infomation that I am using Fedora, which mean's `go env GOPROXY=direct` by default.
I guess you maybe using a goproxy service that it cached `github.com/vartanbeno/go-reddit/v2-v2.0.1`, thus you cannot reproduce this error.

The point is there is not tag v2.0.1 in [vartanbeno/go-reddit](https://github.com/vartanbeno/go-reddit/tags) the github repository anymore, I guess it will be a common error when goproxy server flush its caches.

**Comment by caarlos0** [comment] 2021-09-06 17:25
oh, thanks for pointing that out, fixed on master.

**Closed by caarlos0** 2021-09-06 17:25 UTC
Labels: bug
