### ISSUE TITLE
Template variables and environment variables not being passed to ldflags

### ISSUE THREAD

**Issue by Southclaws** [goreleaser/goreleaser#763] opened 2018-08-18 16:48 UTC
**Describe the bug**

I just had some bug reports from users after a new release and when I asked for them to check their version they reported `master` instead of the expected `1.8.27`. The same thing also affected an environment variable which I used to pass in a Segment.io API key at build time.

The `ldflags` field is set to `s -w -X main.version={{.Version}} -X main.segmentKey={{.Env.SEGMENT_KEY}}`

Some relevant links:

- https://github.com/Southclaws/sampctl/blob/master/.goreleaser.yml#L18
- https://github.com/Southclaws/sampctl/blob/master/.travis.yml#L34
- https://travis-ci.org/Southclaws/sampctl/jobs/417648581#L636

What's odd is that if the environment variable is blank, goreleaser throws an error, and I haven't changed my TravisCI environment variables configuration so I know for sure the variable is there at build (unless TravisCI is at fault).

This is the broken version: https://github.com/Southclaws/sampctl/releases/tag/1.8.27 running the macos binary as `./sampctl version` outputs 1. the missing segment key and 2. the version is `master` instead of `1.8.27`.

**To Reproduce**

https://github.com/Southclaws/sampctl/blob/master/.goreleaser.yml

Use `ldflags` and set either a value to `{{ .Version }}` or an environment variable.

**Expected behavior**

Should pass values to `ldflags`, it worked fine for months.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] linux and mac
- OS version: [uname -a] whatever Travis CI uses
- GoReleaser Version [goreleaser --version] 0.83.0

**Comment by Southclaws** [comment] 2018-08-20 13:32
I found the cause and fixed it, turns out a missing `-` character on `ldflags` silently errored - is this a `go build` bug or a goreleaser issue? I would have expected the `go build` to fail with an invalid ldflags string.

**Comment by caarlos0** [comment] 2018-08-20 13:58
I think it is a go build issue. If go build fails, go releaser fails as well.

You can check that running the go build command directly (if you run with `--verbose` goreleaser prints all the args).

Anyway, since it's not a bug, I'll close the issue :)

**Closed by caarlos0** 2018-08-20 13:58 UTC
