### ISSUE TITLE
Error when trying to upload artifact to github

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [goreleaser/goreleaser#1382] opened 2020-03-07 19:34 UTC
**Describe the bug**

Uploading an artifact fails with the error `422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]`

**To Reproduce**

[Here ](https://github.com/SoMuchForSubtlety/f1viewer/blob/ea960ba2e5a20b3b4bb6f38b7a2951bcbc10b72e/.goreleaser.yml) is my `.goreleaser.yml`

**Expected behavior**

Artifact gets uploaded to release.

**Environment**

Run in a [github action](https://github.com/SoMuchForSubtlety/f1viewer/blob/ea960ba2e5a20b3b4bb6f38b7a2951bcbc10b72e/.github/workflows/release.yml)

**Additional context**
```
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • uploading to release      file=dist/f1viewer_1.0.0_linux_amd64.rpm name=f1viewer_1.0.0_linux_amd64.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=0
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=1
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=2
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=3
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=4
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=5
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=6
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=7
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=8
         • uploading to release      file=dist/f1viewer_1.0.0_linux_386.rpm name=f1viewer_1.0.0_linux_386.rpm
         • failed to upload artifact, will retry artifact=f1viewer_1.0.0_linux_386.rpm try=9
   ⨯ release failed after 84.21s error=GitHub/GitLab/Gitea Releases: failed to publish artifacts: failed to upload f1viewer_1.0.0_linux_386.rpm after 10 retries: POST https://uploads.github.com/repos/SoMuchForSubtlety/f1viewer/releases/24318493/assets?name=f1viewer_1.0.0_linux_386.rpm: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

**Comment by ernado** [comment] 2020-03-15 11:54
Seems like this can be fixed by performing an automated delete on that failed resource after 422 error.
Not sure what is the case, github displays such artifacts as errors and only allows them to be removed.
Probably it can be detected more precisely.

**Comment by caarlos0** [comment] 2020-03-16 15:51
Rather not do that, it might be something else (file manually uploaded for example).

We don't need the retried though, should fail early.

**Comment by caarlos0** [comment] 2020-03-16 15:56
what I don't know is how did the file already exist there on the first upload... maybe some concurrency issue 🤔 

adding more logs to it too

**Comment by ernado** [comment] 2020-03-16 17:54
could be upload that was failed in the middle and then retried

**Comment by caarlos0** [comment] 2020-03-16 18:41
could be, but afaik we don't have a way to know for sure...

**Comment by caarlos0** [comment] 2020-04-12 15:27
BTW we have better logs on this now.

will close this, reopen/open new issue if happens again...

**Closed by caarlos0** 2020-04-12 15:27 UTC
Labels: bug, pinned

**Comment by afritzler** [comment] 2020-05-30 09:07
I am having the same issue here. Did you manage to solve the problem?

**Comment by mooreatv** [comment] 2020-11-10 23:36
I have this issue showing up now for the first time even though it worked before and the asset doesn't actually already exists:

Updating GitHub release: https://github.com/mooreatv/MAMA-multiboxing/releases/tag/v0.4.1
Uploading Mama-v0.4.1.zip... Error (422)
{"message":"Validation Failed","request_id":"0780:5CE7:3580:46FE:5FAB2176","documentation_url":"https://docs.github.com/rest","errors":[{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]}

you can check no such zip exists
https://github.com/mooreatv/MAMA-multiboxing/releases/tag/v0.4.1

I tried again with 0.4.2 to see if it was a fluke and same error
https://github.com/mooreatv/MAMA-multiboxing/actions/runs/356797436

**Comment by caarlos0** [comment] 2020-11-11 15:59
Got some of those myself yesterday, its not a bug on our side, my guess is that's something on github...

https://github.com/goreleaser/nfpm/runs/1382138506?check_suite_focus=true#step:10:157

**Comment by caarlos0** [comment] 2020-11-11 16:01
E.g.:

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/245435/98834410-f0f26100-241d-11eb-9ad1-ac3af22b1107.png">

it doesn't show on the assets list, but if I try to edit it does:


<img width="1161" alt="image" src="https://user-images.githubusercontent.com/245435/98834363-e20bae80-241d-11eb-8e89-ac5bedfec505.png">
