### ISSUE TITLE
Change file location in archive

### ISSUE THREAD

**Issue by lukasmalkmus** [goreleaser/goreleaser#1866] opened 2020-10-20 12:07 UTC
**Is your feature request related to a problem? Please describe.**
I have documentation nested in a couple of directories. When including these with the archive, I don't want the full path to be present but rather have the documentation files on another level in the resulting archive.

**Describe the solution you'd like**
Add a config option to `archives` that allows rewriting file locations in the resulting archive.

**Describe alternatives you've considered**
Channing the documentation location in the repository is not an option.

**Comment by caarlos0** [comment] 2020-10-23 10:45
duplicate of #1638

**Closed by caarlos0** 2020-10-23 10:45 UTC
Labels: enhancement
