### ISSUE TITLE
GitHub release - TLS handshake timeout

### ISSUE THREAD

**Issue by macox** [goreleaser/goreleaser#5145] opened 2024-09-20 09:03 UTC
### What happened?

When upgrading to `2.2.0` I get an error as described in this previous issue https://github.com/goreleaser/goreleaser/issues/5130

The error handling for which is improved by https://github.com/goreleaser/goreleaser/pull/5106
so by using `2.3.0` I can see the actual error, which goes something like:

```shell
     ��� scm releases
       ��� token type                                   type=github
       ��� releasing                                    tag=v0.0.25 repo=my-org/my-repo
       ��� refreshing checksums                         file=my-checksums.txt
       ��� checksumming                                 file=my-app-darwin-amd64.tar.gz
       ��� calculating checksum for dist/my-app-darwin-amd64.tar.gz
       ��� checksumming                                 file=my-app-linux-amd64.tar.gz
       ��� calculating checksum for dist/my-app-linux-amd64.tar.gz
       ��� checksumming                                 file=my-app-darwin-arm64.tar.gz
       ��� calculating checksum for dist/my-app-darwin-arm64.tar.gz
       ��� checksumming                                 file=my-app-windows-amd64.zip
       ��� calculating checksum for dist/my-app-windows-amd64.zip
       ��� could not check rate limits, hoping for the best...
       ��� could not check rate limits, hoping for the best...
       ��� release creation failed                      name=v0.0.531 error=Post "https://api.github.com/repos/my-org/my-repo/releases": net/http: TLS handshake timeout
       ��� took: 40s
   ��� took: 40s
   ��� release failed after 6m24s               error=scm releases: failed to publish artifacts: could not release: Post "https://api.github.com/repos/my-org/my-repo/releases": net/http: TLS handshake timeout
```

### How can we reproduce this?

As described in https://github.com/goreleaser/goreleaser/issues/5130

### goreleaser version

```bash
v2.3.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2024-09-20 12:27
that looks like a timeout from github...

**Comment by caarlos0** [comment] 2024-09-20 13:23
likely some issue in either your internet connection or GitHub... trying again might fix it.

you may also try to curl that endpoint to see if it resolves

nevertheless, probably not a bug, so I'm closing this

**Comment by macox** [comment] 2024-09-20 13:35
> likely some issue in either your internet connection or GitHub... trying again might fix it.
> 
> you may also try to curl that endpoint to see if it resolves
> 
> nevertheless, probably not a bug, so I'm closing this

I've tried numerous times and it always fails. pre-2.2.0 always passes, so hopefully you can see why I came here.

**Comment by caarlos0** [comment] 2024-09-20 13:57
are you running it locally? can you provide a reproducible?

**Comment by macox** [comment] 2024-09-25 14:08
> are you running it locally? can you provide a reproducible?

So running it locally seems to work fine.
The problem happens when running within a (Jenkins) pipeline, which I realise points to an issue my end, but as part of the same pipeline I am contacting github numerous times.

**Comment by caarlos0** [comment] 2024-09-25 14:33
i mean, if it was something on goreleaser, i would have a dozen issues about this already... 

i'm trying to figure out if you're doing anything different than most... if you can share your pipeline config that might help shed some light on the issue... so far i have no idea as i can't reproduce and it doesn't happen with anyone else as far as i know

**Comment by macox** [comment] 2024-09-25 15:55
> i mean, if it was something on goreleaser, i would have a dozen issues about this already...
> 
> i'm trying to figure out if you're doing anything different than most... if you can share your pipeline config that might help shed some light on the issue... so far i have no idea as i can't reproduce and it doesn't happen with anyone else as far as i know

Yeah, I appreciate your time, so I've simplified it so that it downloads goreleaser as it needs it. Just have this in the pipeline now

```
sh "curl -Lf https://github.com/goreleaser/goreleaser/releases/download/v2.3.2/goreleaser_Linux_x86_64.tar.gz | tar xzf - goreleaser"
sh "mv goreleaser /usr/local/bin/"
sh "goreleaser --version"
sh "goreleaser release --config=.goreleaser.yml"
```

**Comment by caarlos0** [comment] 2024-09-25 16:45
yeah, that seems like it should work 🤔 

I'm looking through the diff of v2.1.0 and v2.3.2, and I don't see how this could have been broken, except if maybe some dependency update (maybe x/net?)

https://github.com/goreleaser/goreleaser/compare/v2.1.0...v2.3.2

**Comment by macox** [comment] 2024-09-26 08:17
> yeah, that seems like it should work 🤔
> 
> I'm looking through the diff of v2.1.0 and v2.3.2, and I don't see how this could have been broken, except if maybe some dependency update (maybe x/net?)
> 
> [v2.1.0...v2.3.2](https://github.com/goreleaser/goreleaser/compare/v2.1.0...v2.3.2)

So it appears when I go to v2.2.0, but I can't see anything obvious that would break it. Really confusing.

**Comment by caarlos0** [comment] 2024-09-27 13:40
2.2.0 was the first release built with go 1.23... I wonder if there's something there? 🤔 


- v2.1.0: https://github.com/goreleaser/goreleaser/actions/runs/9921787707/job/27410129891#step:7:28
-  v2.2.0: https://github.com/goreleaser/goreleaser/actions/runs/10397740910/job/28793936760#step:7:38

**Comment by caarlos0** [comment] 2024-09-27 13:42
> Linux[¶](https://go.dev/doc/go1.23#linux)
> 
> Go 1.23 is the last release that requires Linux kernel version 2.6.32 or later. Go 1.24 will require Linux kernel version 3.2 or later.

maybe old linux kernel on your side?

https://go.dev/doc/go1.23#linux

**Comment by macox** [comment] 2024-10-01 10:33
> > Linux[¶](https://go.dev/doc/go1.23#linux)
> > Go 1.23 is the last release that requires Linux kernel version 2.6.32 or later. Go 1.24 will require Linux kernel version 3.2 or later.
> 
> maybe old linux kernel on your side?
> 
> https://go.dev/doc/go1.23#linux

Thanks for this, and good thinking. Looks we're on a much later version though.

I'm happy for you to close this if you wish, if I find out what the issue is I will post it back here

**Comment by macox** [comment] 2024-10-09 14:36
@caarlos0 I've figured out a workaround for this, it's related to https://tip.golang.org/doc/go1.23#cryptotlspkgcryptotls

> The experimental post-quantum key exchange mechanism X25519Kyber768Draft00 is now enabled by default when [Config.CurvePreferences](https://tip.golang.org/pkg/crypto/tls#Config.CurvePreferences) is nil. The default can be reverted by adding tlskyber=0 to the GODEBUG environment variable.

So getting `GODEBUG="tlskyber=0` when using goreleaser gets working for me.
`godebug tlskyber=0` can also be set in `go.mod`

**Comment by caarlos0** [comment] 2024-10-09 15:14
oh, that's weird 🤔 

I wonder why it only happens for you though? Maybe something on your jenkins box? Or something GitHub actions does that is missing on your side? 🤔

**Closed** 2024-10-14 12:41 UTC
