### ISSUE TITLE
Bug: Goreleaser creates DEB packages but fails when installing the DEB, due to "bindir" in .goreleaser

### ISSUE THREAD

**Issue by jportasa** [goreleaser/goreleaser#1842] opened 2020-10-06 14:38 UTC
**Describe the bug**

.goreleaser creates the .deb without errors but when I do dpkg -i <name>.deb fails with error:
Seems it is due to:
bindir: /var/db/newrelic-infra/newrelic-integrations/bin
if I remove "-" it works fine.

root@0f95f7bf53a9:/dist# dpkg -i nri-kafka_2.9.8-1_amd64.deb
Selecting previously unselected package nri-kafka.
(Reading database ... 4122 files and directories currently installed.)
Preparing to unpack nri-kafka_2.9.8-1_amd64.deb ...
Unpacking nri-kafka (2.9.8) ...
dpkg: error processing archive nri-kafka_2.9.8-1_amd64.deb (--install):
 unable to install new version of '/var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka': Not a directory
Errors were encountered while processing:
 nri-kafka_2.9.8-1_amd64.deb

**To Reproduce**

```yaml
before:
  hooks:
  # You may remove this if you don't use go modules.
  #- go mod download
  # you may remove this if you don't need go generate
  #- go generate ./...
  #- make validate

builds:
  - id: nri-kafka-nix
    main: ./src
    binary: nri-kafka
    gobinary: "go1.9.7"
    #ldflags:
    #  - -s -w -X github.com/newrelic/nri-flex/internal/load.IntegrationVersion={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: nri-kafka-deb
    builds:
      - nri-kafka-nix
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    vendor: "New Relic, Inc."
    homepage: "https://www.newrelic.com/infrastructure"
    maintainer: "New Relic Infrastructure Team <infrastructure-eng@newrelic.com>"
    description: "New Relic Infrastructure kafka Integration extend the core New Relic\nInfrastructure agent's capabilities to allow you to collect metric and\nlive state data from kafka components."
    license: "https://newrelic.com/terms (also see LICENSE.txt installed with this package)"
    # Formats to be generated.
    formats:
      - deb
    bindir: /var/db/newrelic-infra/newrelic-integrations/bin
    files:
      "kafka-config.yml.sample": "/etc/newrelic-infra/integrations.d"
      "kafka-definition.yml": "/var/db/newrelic-infra/newrelic-integrations"
      "CHANGELOG.md": "/usr/share/doc/nri-kafka"
      "README.md":  "/usr/share/doc/nri-kafka"
      "LICENSE": "/usr/share/doc/nri-kafka"
    dependencies:
      - "newrelic-infra"

# we use custom publisher for fixing archives and signing them
release:
  disable: true
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

*** Installation fails if bindir: /var/db/newrelic-infra/newrelic-integrations/bin  (hypens in the path)

*** Installation works fine if bindir without hypens:  bindir: /var/db/newrelicinfra/newrelicintegrations/bin
root@27487f74cf09:/dist# dpkg --contents nri-kafka_2.9.7-1_amd64.deb
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/db/
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/db/newrelicinfra/
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/db/newrelicinfra/newrelicintegrations/
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/db/newrelicinfra/newrelicintegrations/bin/
-rwxr-xr-x 0/0         9759040 2020-10-06 14:24 var/db/newrelicinfra/newrelicintegrations/bin/nri-kafka
drwxr-xr-x 0/0               0 2020-10-06 14:24 usr/
drwxr-xr-x 0/0               0 2020-10-06 14:24 usr/share/
drwxr-xr-x 0/0               0 2020-10-06 14:24 usr/share/doc/
-rw-r--r-- 0/0            5083 2020-10-06 14:24 usr/share/doc/nri-kafka
-rw-r--r-- 0/0            1063 2020-10-06 14:24 usr/share/doc/nri-kafka
-rw-r--r-- 0/0            5392 2020-10-06 14:24 usr/share/doc/nri-kafka
drwxr-xr-x 0/0               0 2020-10-06 14:24 etc/
drwxr-xr-x 0/0               0 2020-10-06 14:24 etc/newrelic-infra/
-rw-r--r-- 0/0            9004 2020-10-06 14:24 etc/newrelic-infra/integrations.d
drwxr-xr-x 0/0               0 2020-10-06 14:24 var/db/newrelic-infra/
-rw-r--r-- 0/0             496 2020-10-06 14:24 var/db/newrelic-infra/newrelic-integrations

and I don't get the error:

root@27487f74cf09:/dist# dpkg -i nri-kafka_2.9.7-1_amd64.deb
(Reading database ... 4132 files and directories currently installed.)
Preparing to unpack nri-kafka_2.9.7-1_amd64.deb ...
Unpacking nri-kafka (2.9.7) over (2.9.7) ...
dpkg: dependency problems prevent configuration of nri-kafka:
 nri-kafka depends on newrelic-infra; however:
  Package newrelic-infra is not installed.

dpkg: error processing package nri-kafka (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nri-kafka

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] Mac runs goreleaser and Ubuntu18..04 tries to install the deb
- OS version: [uname -a] ubuntu18.04
- GoReleaser Version [goreleaser --version]  version: 0.131.1
- GitLab version (if using a private hosted one)

**Comment by caarlos0** [comment] 2020-10-06 21:29
The problem is clear in the error log:

```
dpkg: dependency problems prevent configuration of nri-kafka:
nri-kafka depends on newrelic-infra; however:
Package newrelic-infra is not installed.
```

Anyway, I just generated some deb packages with goreleaser and hyphens in their names (and with dependencies as well), and all of them worked as expected.

This issue seems invalid to me, closing for now, let me know if I got this wrong.

Cheers

**Closed by caarlos0** 2020-10-06 21:29 UTC
Labels: bug

**Comment by caarlos0** [comment] 2020-10-06 21:33
EDIT: improving formatting in the OP

**Comment by caarlos0** [comment] 2020-10-06 21:36
> * GoReleaser Version [goreleaser --version]  version: 0.131.1

just noticed this, can you try with a more recent version?

**Comment by jportasa** [comment] 2020-10-07 07:54
We have used goreleaser version 0.143.0 and happens the same. Runing it in a MAC or in a Ubuntu. DEB package is not correctly created

**Comment by jportasa** [comment] 2020-10-07 07:56
Carlos, have you installed the DEB in a ubuntu?  try this:  docker run -it -v /Users/mac/repos/nri-kafka/dist:/dist -w /dist ubuntu:16.04 bash   and next dpkg -i  name.deb

**Comment by caarlos0** [comment] 2020-10-07 12:25
yes, tried on multiple ubuntu versions even.

If you can provide a reproducible of the issue (go code + goreleaser config with the bare minimum for it to happen) I can take a look...
