### ISSUE TITLE
Create multiple archive types

### ISSUE THREAD

**Issue by gabeduke** [goreleaser/goreleaser#874] opened 2018-11-14 03:35 UTC
**Is your feature request related to a problem? Please describe.**
In order to publish both to a binary archive and a package archive (eg. github release and artifactory) it is necessary to build 2 separate `.goreleaser.yml` files.

**Describe the solution you'd like**
Allow multiple archive stages and then call them by name in the publish steps. (similar to multi-stage dockerfiles).
* artifactory publisher: `src: bin-archiver`
* [github] release: `src: default-archiver`

**Comment by caarlos0** [comment] 2018-11-14 11:30
hi, yes, there was a WIP PR about that but I hit a wall, will work on it again soon... 

https://github.com/goreleaser/goreleaser/pull/787

**Comment by soupdiver** [comment] 2018-11-23 09:06
I had a look at the other PR. I'm not that familiar with the codebase yet.
Could you explain a bit what was the show stopper in the end and why it was way harder to implement than initially thought?

**Comment by caarlos0** [comment] 2018-11-23 15:14
Lot's of refactoring, and... I don't remember quite sure without reading the PR again, but I think it was that some pipes backreference things from the archive all assuming that there will be only one one, so the main thing is to find a way for the user to tell which, e.g., brew setting should use which archive setting... I will probably end up adding an `id` field or something like that...

that being said, I would need to add some kind of config validation at some point, probably similar to what we have for defaults, so, more refactory... 

anyway, haven't been thinking much about this recently as life has been crazy, but eventually I'll tackle this - possibly splitting it in more parts instead of a single big-as-hell PR.

**Comment by caarlos0** [comment] 2018-12-17 16:18
duplicate of #705

**Closed by caarlos0** 2018-12-17 16:18 UTC
Labels: enhancement, pinned
