### ISSUE TITLE
Releasing to GitHub stage fails with 404

### ISSUE THREAD

**Issue by Southclaws** [goreleaser/goreleaser#724] opened 2018-07-15 13:22 UTC
**Describe the bug**

TravisCI has broken (not sure why, API outage or something) so I had to release a new version manually. Upon trying this, I'm getting the following error right at the end of the process under the `RELEASING TO GITHUB` section:

```
   • RELEASING TO GITHUB
      • creating or updating release repo=Southclaws/sampctl tag=1.8.18
      • release updated           url=
   ⨯ release failed after 107.69s error=POST https://api.github.com/repos/Southclaws/sampctl/releases: 404 Not Found []
```

**To Reproduce**

I'm not really sure how to reproduce - maybe try running goreleaser inside https://github.com/Southclaws/sampctl/ I don't know if it will reproduce but I've managed to reproduce it on two systems so far (Mac and an Ubuntu server)

See https://github.com/Southclaws/sampctl/tree/master/.goreleaser.yml

**Expected behavior**

A successful build, all the rest up to this point worked okay.

**Environment (please complete the following information):**

- OS: mac and ubuntu
- OS version: `Linux southclaws 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- GoReleaser Version latest commit as of this post, also tried 0.80.1 on mac

**Comment by caarlos0** [comment] 2018-07-16 13:08
hi @Southclaws, did you renamed your repository or something?

did it happen to other repos, or just this one?

**Comment by Southclaws** [comment] 2018-07-16 13:33
No renames, and I only use goreleaser for this project.

**Comment by caarlos0** [comment] 2018-07-16 13:48
hmmm that's weird... I just did a release 2 days ago and it worked https://github.com/caarlos0/domain_exporter/releases

will try to update the github package... not sure if it is related though...

**Comment by caarlos0** [comment] 2018-07-19 23:27
@Southclaws are you still being able to reproduce this?

**Comment by caarlos0** [comment] 2018-07-21 13:40
closing as I couldn't reproduce.

**Closed by caarlos0** 2018-07-21 13:40 UTC

**Comment by Southclaws** [comment] 2018-07-21 18:40
Could this be because I am trying to release an app that's stored in an organisation's repository and my token doesn't have access?

**Comment by caarlos0** [comment] 2018-07-21 22:30
> Could this be because I am trying to release an app that's stored in an organisation's repository and my token doesn't have access?

yeah, can be... you can generate a new token just to be sure... this doesn't seem to be a bug in goreleaser though...


maybe github support can help as well...

**Comment by cloudrkt** [comment] 2018-10-19 13:47
Just ran into the same issue. Your token needs to acces public repo's.

**Comment by marataziat** [comment] 2019-04-01 05:34
I have this issue too :(
```
   ⨯ release failed after 4.86s error=GitHub Releases: failed to publish artifacts: POST https://api.github.com/repos/marataziat/subfinde/releases: 404 Not Found []
```
even if my repo is created!
