### ISSUE TITLE
Unable to posts to GitHub when using SSH

### ISSUE THREAD

**Issue by pmichali** [goreleaser/goreleaser#570] opened 2018-02-20 16:42 UTC
### Prerequisites

* [ ] Are you running the latest version? Yes
* [ ] Did you perform a search to see if this problem was already reported? Yes

For more information, see the `CONTRIBUTING` guide.

### Description

When I tried to create a release, I got a post error indicating 404 not found.

### Environment

Please paste the output of:

* `go version`  go version go1.9.2 linux/amd64
* `uname -a` Linux bxb-c2-77 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* `goreleaser --debug`

```
• releasing...
   • loading config file       file=.goreleaser.yml
   • SETTING DEFAULTS FOR:
      • loading environment variables
      • snapshoting
      • releasing to GitHub
      • creating archives
      • building binaries
      • creating Linux packages with fpm
      • creating Linux packages with nfpm
      • creating Linux packages with snapcraft
      • calculating checksums
      • signing artifacts
      • creating Docker images
      • releasing to Artifactory
      • creating homebrew formula
      • creating Scoop Manifest
   • CHECKING ./DIST
      • --rm-dist is set, cleaning it up
   • GETTING AND VALIDATING GIT STATE
      • releasing v1.0.0, commit 9f14b0256d90854c122f53450fe780abab67e5bd
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
   • LOADING ENVIRONMENT VARIABLES
   • BUILDING BINARIES
      • building                  binary=dist/linux_amd64/lazyjack
      • building                  binary=dist/linux_386/lazyjack
      • added new artifact        name=lazyjack path=dist/linux_amd64/lazyjack type=%!s(artifact.Type=2)
      • added new artifact        name=lazyjack path=dist/linux_386/lazyjack type=%!s(artifact.Type=2)
   • CREATING ARCHIVES
      • creating                  archive=dist/lazyjack_1.0.0_linux_amd64.tar.gz
      • creating                  archive=dist/lazyjack_1.0.0_linux_386.tar.gz
      • added new artifact        name=lazyjack_1.0.0_linux_386.tar.gz path=dist/lazyjack_1.0.0_linux_386.tar.gz type=%!s(artifact.Type=0)
      • added new artifact        name=lazyjack_1.0.0_linux_amd64.tar.gz path=dist/lazyjack_1.0.0_linux_amd64.tar.gz type=%!s(artifact.Type=0)
   • CREATING LINUX PACKAGES WITH FPM
      • skipped                   reason=no output formats configured
   • CREATING LINUX PACKAGES WITH NFPM
      • skipped                   reason=no output formats configured
   • CREATING LINUX PACKAGES WITH SNAPCRAFT
      • skipped                   reason=no summary nor description were provided
   • CALCULATING CHECKSUMS
      • added new artifact        name=lazyjack_1.0.0_checksums.txt path=dist/lazyjack_1.0.0_checksums.txt type=%!s(artifact.Type=5)
      • checksumming              file=lazyjack_1.0.0_linux_386.tar.gz
      • checksumming              file=lazyjack_1.0.0_linux_amd64.tar.gz
   • SIGNING ARTIFACTS

You need a passphrase to unlock the secret key for
user: "*******"
4096-bit RSA key, ID *****

      • added new artifact        name=lazyjack_1.0.0_checksums.txt.sig path=dist/lazyjack_1.0.0_checksums.txt.sig type=%!s(artifact.Type=6)
   • CREATING DOCKER IMAGES
      • skipped                   reason=docker section is not configured
   • RELEASING TO ARTIFACTORY
      • skipped                   reason=artifactory section is not configured
   • RELEASING TO GITHUB
      • creating or updating release repo=git@github-k8s:pmichali/lazyjack tag=v1.0.0
      • release updated           url=
   ⨯ release failed after 50.77s error=POST https://api.github.com/repos/git@github-k8s:pmichali/lazyjack/releases: 404 Not Found []
```

### Steps to Reproduce

Tried running goreleaser, on a system that uses SSH to access repo, instead of HTTPS. Looks like URL is malformed.

My .goreleaser.yml had just the bare entries:
```
# .goreleaser.yml
builds:
  - main: ./cmd/lazyjack.go
    binary: lazyjack
    goos:
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  files:
    - LICENSE
    - sample-config.yaml
sign:
  artifacts: checksum
```

**Expected behavior:** [What you expected to happen]
Release to be pushed up to GitHub

**Actual behavior:** [What actually happened]
Failed to push up.

**Comment by pmichali** [comment] 2018-02-20 16:44
From slack Carlos suggested to add the following to the .goreleaser.yml file:
```
release:
  github:
    owner: REPO_OWNER
    name: REPO_NAME
```
Doing this resolved the issue and the push worked.

**Comment by caarlos0** [comment] 2018-02-20 17:02
hey @pmichali , thanks for opening the issue!

can you also paste the output of `git remote -v`?

I always use SSH and I can release just fine, eg:

```
~/Code/Go/src/github.com/goreleaser/goreleaser master*
λ git remote -v
origin	git@github.com:goreleaser/goreleaser.git (fetch)
origin	git@github.com:goreleaser/goreleaser.git (push)
```

**Comment by pmichali** [comment] 2018-02-20 18:53
```
origin	git@github-k8s:pmichali/lazyjack.git (fetch)
origin	git@github-k8s:pmichali/lazyjack.git (push)
```

Where github-k8s maps to a SSH config that sets the host, port, user, and SSH key file.

When I added the github lines to my .goreleaser.yml file (as mentioned in previous comment), the push worked fine.

**Comment by pmichali** [comment] 2018-02-20 18:55
Is it possible that the issue is because of the redirection done with the SSH host? I do that so multiple repos for different github projects with different SSH keys, can be supported.

**Comment by caarlos0** [comment] 2018-02-20 19:00
yes, the problem is that goreleaser assumes github.com:user/repo.git

that could probably be improved though.

thanks for reporting this!

**Comment by caarlos0** [comment] 2018-02-20 21:22
fixed on latest!

thanks!

**Closed** 2018-02-20 21:21 UTC
Labels: bug
