### ISSUE TITLE
Prevent checksums file from uploading

### ISSUE THREAD

**Issue by NorseGaud** [goreleaser/goreleaser#1847] opened 2020-10-09 20:44 UTC
**Describe the bug**

```
builds:
  - id: builder
    binary: binary-name
    env:
      # Because we want to avoid coupling to system libraries.
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: zip
    builds:
      - builder
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

signs:
  - id: notarize-zip
    signature: "${artifact}.zip"
    cmd: gon
    args:
      - ".gon.hcl"
    artifacts: all
    ids:
      - builder

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/*.zip
```

Using this yaml, I can notarize my zip/binary. However, the checksums file contents is then different from what the new signed/notarized .zip is.

There should be a way to disable the uploading of the checksums.txt file.

**Comment by caarlos0** [comment] 2020-10-10 11:50
seems like a duplicate of #1802

**Closed by caarlos0** 2020-10-10 11:50 UTC
Labels: enhancement

**Comment by caarlos0** [comment] 2020-10-10 11:55
BTW you can already disable the checksum thing: https://goreleaser.com/customization/checksum/

**Comment by NorseGaud** [comment] 2020-10-10 14:47
@caarlos0 , disabling checksum prevents signing. Is that a bug?

**Comment by caarlos0** [comment] 2020-10-10 15:41
> disabling checksum prevents signing. Is that a bug?

yes, seems like a bug 🤔

**Comment by NorseGaud** [comment] 2020-10-10 19:48
I’ll follow up after the three day weekend and get you everything you need

👍🏻 Thanks for the help

**Comment by caarlos0** [comment] 2020-10-13 14:03
Thanks @NorseGaud 🙏
