### ISSUE TITLE
I'd like to use the nfpm symlinks feature

### ISSUE THREAD

**Issue by rgroleau** [goreleaser/goreleaser#1861] opened 2020-10-18 14:42 UTC
Although nfpm (for deb) supports the symlinks: [option](https://github.com/goreleaser/nfpm/pull/185), I get the error:
`error=yaml: unmarshal errors: field symlinks not found in type config.NFPM`
whenever trying to add symlinks: statements,
most likely because it is missing from goreleaser config?

This feature is quite nice for systemd service files.
Now I will have to code a post installation script just to maintain that link...
But this seem like a rather trivial change (I think, but then again I am often wrong, so sorry in advance).
Thanks!

**Comment by caarlos0** [comment] 2020-10-23 14:38
duplicate of https://github.com/goreleaser/goreleaser/issues/1829

**Comment by SKalt** [comment] 2020-11-15 20:32
If possible, I'd like to reopen this issue since issue #1829  was closed with PR #1849, which includes support for packager-specific nfpm configuration options but doesn't include support for nfpm's symlink option.
Let me know if I should open a new issue.

**Comment by caarlos0** [comment] 2020-11-16 00:18
yeah seems like symlinks weren't ported

**Closed** 2020-11-27 02:45 UTC
Labels: duplicate

**Comment by hellt** [comment] 2020-12-02 09:37
can confirm that with 0.149.0 the symlink feature works
