### ISSUE TITLE
build fail - unknown field 'Format' in struct literal of type tar.Header

### ISSUE THREAD

**Issue by vjeantet** [goreleaser/goreleaser#590] opened 2018-03-01 18:52 UTC
My travis recipe failed to build today, I did not change anything..

Do you know where this issue could come from ?

```
go get github.com/goreleaser/goreleaser && goreleaser --skip-validate
# github.com/goreleaser/nfpm/deb
../../goreleaser/nfpm/deb/deb.go:132:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:191:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:215:10: unknown field 'Format' in struct literal of type tar.Header
```

Thanks

**Comment by caarlos0** [comment] 2018-03-01 19:34
Hi @vjeantet, seems like a duplicate of #588 and #589

**Closed by caarlos0** 2018-03-01 19:34 UTC
