### ISSUE TITLE
[PRO] Nightly stopped publishing releases

### ISSUE THREAD

**Issue by aymanbagabas** [goreleaser/goreleaser#3541] opened 2022-11-09 16:47 UTC
### What happened?

The nightly release doesn't get published even though `publish_release` is set to `true`. It creates a draft release without publishing it on GitHub.

### How can we reproduce this?

```yml
nightly:
  name_template: "{{ .ShortCommit }}-devel"
  publish_release: true
  keep_single_release: true
  tag_name: nightly
```

### goreleaser version

`goreleaser v1.12.3-pro`

<details>
<summary>log</summary>

```
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/1.12.3-pro/x64/goreleaser release --rm-dist --nightly
  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v1.12.3-pro
  • starting release...
  • loading config file                              file=.goreleaser.yml
  • loading environment variables
  • getting and validating git state
    • building...                                    commit=8341c17e16fea093856c9432439e97d72e57d3a7 latest tag=v3.3.0
    • pipe skipped                                   reason=validation is disabled
  • parsing tag
  • setting defaults
  • running before hooks
    • running hook                                   hook=rm -rf static
    • running hook                                   hook=go run .
    • took: 42s
  • nightly
    • building nightly...                            version=8341c17-devel
  • checking distribution directory
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • adjusting internal git state
  • generating changelog
    • writing                                        changelog=dist/CHANGELOG.md
  • building binaries
    • skip is set                                    id=PROJECT
  • archives
    • creating                                       archive=dist/PROJECT-devel.tar.gz
    • took: 1s
  • calculating checksums
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • publishing
    • scm releases
      • creating or updating release                 repo=USER/PROJECT tag=8341c17e16fea093856c9432439e97d72e57d3a7
      • deleted previous nightly pre-release         commit=main name=e393ee05486deccd8be8d78c71a9fafe6c7fbbea tag=nightly
      • deleted previous nightly tag
      • uploading to release                         file=dist/PROJECT-devel_checksums.txt name=PROJECT-devel_checksums.txt
      • uploading to release                         file=dist/PROJECT-devel.tar.gz name=PROJECT-devel.tar.gz
      • published                                    url=https://github.com/USER/PROJECT/releases/tag/nightly
      • took: 4s
  • took: 4s
  • release succeeded after 47s
  • thanks for using goreleaser-pro!
```

</details>

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2022-11-09 16:51
Hmmm I saw that happening a couple of times myself... I'm not sure why, it might be some sort of github api bug... will look into it once more. Thanks for reporting ayman! 🙏

**Comment by caarlos0** [comment] 2022-11-12 19:01
yes, this definitely looks like some sort of bug in github... will come up with a workaround though...

**Comment by caarlos0** [comment] 2022-11-18 02:43
just tested it multiple times in a project of mine, got it to reproduce the issue once, even with this patch... I have no idea why it happens though... 

I'm thinking... maybe some caching thing when deleting the previous nightly tag? I have no idea at this point :(

**Comment by caarlos0** [comment] 2022-11-18 02:54
okay, at this point I'm fairly sure this is a github bug... opened a ticket for them, will revert part of #3547 


https://support.github.com/ticket/personal/0/1883035 <- probably not visible for y'all, but just so I can track it later.

**Comment by caarlos0** [comment] 2022-11-30 11:02
added request id logs so we can track this in the future, as github support also can't reproduce this

**Comment by caarlos0** [comment] 2023-01-28 03:30
after many exchanged emails, my best guess is that its some sort of eventual consistency issue on github, so I added a 5s sleep after deleting the release & tag to prevent re-creating it right away

what seems to be happening is that both the release deletion and creation requests arrive at the same time/out of order, so the creation is processed first (which we then handle as an edit) and after that it deletes it, then when we edit it, because the tag was deleted, it set the release to draft.

I did test it a bit and it seems to be working, so I'll close this once v1.15 is released if everything works out well :)

**Closed** 2023-02-10 13:34 UTC
Labels: bug, pro
