### ISSUE TITLE
No buildable Go source files

### ISSUE THREAD

**Issue by jhaynie** [goreleaser/goreleaser#263] opened 2017-06-20 16:25 UTC
I'm using the latest release 0.20.4 trying to add goreleaser to a new project.  When I run using defaults created with `init` I get the following:

```
Running goreleaser 0.20.4
Setting defaults
Getting and validating git state
Loading environment variables
Building binaries
 -> Building dist/pinpt_0.0.1_linux_amd64/pinpt
 -> Building dist/pinpt_0.0.1_linux_386/pinpt
 -> Building dist/pinpt_0.0.1_darwin_386/pinpt
 -> Building dist/pinpt_0.0.1_darwin_amd64/pinpt
build failed: darwin/386
go build github.com/pinpt/worker/vendor/gopkg.in/libgit2/git2go.v24: no buildable Go source files in /Users/jhaynie/go/src/github.com/pinpt/worker/vendor/gopkg.in/libgit2/git2go.v24
```

I'm using the libgit2 package in my project.  When i build using `go build ./` go builds a darwin binary fine. I can't seem to figure out why it's getting this error.  I also can't figure out how to turn on more debug logging.  

Any ideas?

**Comment by caarlos0** [comment] 2017-06-20 17:06
Hi @jhaynie, can you cat your `goreleaser.yml` file and paste it in here please?

**Comment by jhaynie** [comment] 2017-06-20 17:40
```
release:
  github:
    owner: pinpt
    name: worker
brew:
  github: {}
  install: bin.install "pinpt"
build:
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: pinpt
  hooks: {}
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
fpm: {}
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
```

**Comment by jhaynie** [comment] 2017-06-20 17:40
essentially this is the template from `init`. I only changed the binary name

**Comment by jhaynie** [comment] 2017-06-20 17:41
interestingly, when i run `go build ./` and build the binary and transfer it to a clean machine, the binary as a linker issue around the libgit2. I guess it must be dynamically linking (which makes sense) this binary.  might be unrelated

**Comment by caarlos0** [comment] 2017-06-20 17:59
@jhaynie can you try it removing the `-s -w` ldflags?

**Comment by jhaynie** [comment] 2017-06-20 19:46
same error.

**Comment by caarlos0** [comment] 2017-06-20 20:02
> build failed: darwin/386

it always fails for darwin/386, or fail for other targets too? Can you try removing this target and see if it works?

**Comment by jhaynie** [comment] 2017-06-20 20:03
yeah, i tried just linux and it fails for it too.

**Comment by jhaynie** [comment] 2017-06-20 20:08
it fails for all targets no matter which one i remove or keep. so i tried different combinations.  

is there any sort of verbose logging we could turn on?

**Comment by caarlos0** [comment] 2017-06-20 20:30
> is there any sort of verbose logging we could turn on?

@jhaynie no, but it's a good thing to add

The build will basically be something like `GOOS=os GOARCH=arch go build -ldflags -o name .`, as you can see [here](https://github.com/goreleaser/goreleaser/blob/master/pipeline/build/build.go#L64).

Meanwhile, I'll open a PR adding a debug flag.

**Comment by jhaynie** [comment] 2017-06-20 20:44
ok, cool. once you create a PR i can test from it and see what we get

**Comment by caarlos0** [comment] 2017-06-22 04:06
hey @jhaynie , sorry for the delay, can you check #264?

**Comment by caarlos0** [comment] 2017-06-22 17:14
@jhaynie latest versions have a `--debug` flag, can you try it?

**Comment by osteele** [comment] 2017-07-12 22:53
I'm seeing this issue too. The presence of `import "C"` in a file seems to hide it from the build, so that any symbols defined in that file are unavailable.

I'm running on macOS Sierra 10.12.5.  My test repo is <https://github.com/osteele/goreleaser-issue>. It already has a tag v0.0.1, created via `git tag -af v0.0.1 -m "First release" && git push -n origin +v0.0.1`. Note that the `global` variable, defined in `global.go`, is available to `go build` and `go run`, but not to `goreleaser`.

There is no `.goreleaser.yml` file. I pared it down more and more, until it turned out to be unnecessary.

Following is a short transcript showing the issue, followed by a longer transcript with `--debug`. It appears that maybe the problem is cross-compiling the Linux version? A further step would be to add back a `.goreleaser.yml` that removes the Linux target; I timed out on preparing this bug report before I got to that.

This case is isolated from a real-world case <https://github.com/osteele/gojekyll> where I'd like to use goreleaser. The build for that case hits the issue twice: once with a file `strftime/strftime.go` in the repo itself, and once with the <https://github.com/wellington/go-libsass> library that it depends on. go-libsass doesn't build because its `lib/encoding.go` contains an `import "C"` and is therefore ignored. I can supply more details about that case if this isolation isn't sufficient.

```
$ go version go1.8.3 darwin/amd64
go version go1.8.3 darwin/amd64
$ goreleaser --version
goreleaser version 0.26.1, commit b7c93a213e6628a6a1bd27fe31942d929836050f, built at 2017-07-10T12:18:00Z
$ go build .
global = 1
$ go run *.go
global = 1
To https://github.com/osteele/goreleaser-issue.git
 * [new tag]         v0.0.1 -> v0.0.1
   • running goreleaser dev
   • loading config file       file=.goreleaser.yml
   • SETTING DEFAULTS
   • GETTING AND VALIDATING GIT STATE
   • LOADING ENVIRONMENT VARIABLES
   • CHECKING ./DIST
   • BUILDING BINARIES
   • skipped ignored build     target=darwin/386
   • new folder                folder=goreleaser-issue_0.0.1_macOS_64bit key=darwinamd64
   • building                  binary=dist/goreleaser-issue_0.0.1_macOS_64bit/goreleaser-issue
   • new folder                folder=goreleaser-issue_0.0.1_Linux_32bit key=linux386
   • building                  binary=dist/goreleaser-issue_0.0.1_Linux_32bit/goreleaser-issue
   • new folder                folder=goreleaser-issue_0.0.1_Linux_64bit key=linuxamd64
   • building                  binary=dist/goreleaser-issue_0.0.1_Linux_64bit/goreleaser-issue
   ⨯ release failed            error=build failed for darwin/amd64:
# github.com/osteele/goreleaser-issue
./main.go:6: undefined: global
```

```
goreleaser --rm-dist --debug
   • running goreleaser 0.26.1
   • could not load config, using defaults file=.goreleaser.yml
   • SETTING DEFAULTS 
   • defaults set              config={goreleaser-issue {osteele/goreleaser-issue false map[]} {/    bin.install "goreleaser-issue" [] []   map[]} [{[linux darwin] [amd64 386] [6] [] . -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}  goreleaser-issue {  map[]} [] map[]}] {tar.gz [] {{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }} map[] [licence* LICENCE* license* LICENSE* readme* README* changelog* CHANGELOG*] map[]} {[] [] []      map[]} {SNAPSHOT-{{ .Commit }} map[]} {[] [] [] []     {  map[]} [] map[]} dist map[]}
   • GETTING AND VALIDATING GIT STATE
   • LOADING ENVIRONMENT VARIABLES
   • CHECKING ./DIST  
   • rm-dist is set, removing ./dist
   • BUILDING BINARIES
   • building                  build={[linux darwin] [amd64 386] [6] [] . -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}  goreleaser-issue {  map[]} [] map[]}
   • new folder                folder=goreleaser-issue_0.0.1_darwin_amd64 key=darwinamd64
   • building                  binary=dist/goreleaser-issue_0.0.1_darwin_amd64/goreleaser-issue
   • new folder                folder=goreleaser-issue_0.0.1_darwin_386 key=darwin386
   • building                  binary=dist/goreleaser-issue_0.0.1_darwin_386/goreleaser-issue
   • new folder                folder=goreleaser-issue_0.0.1_linux_386 key=linux386
   • building                  binary=dist/goreleaser-issue_0.0.1_linux_386/goreleaser-issue
   • running                   cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_darwin_amd64/goreleaser-issue .] env=[GOOS=darwin GOARCH=amd64 GOARM=] target=darwin/amd64
   • running                   cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_linux_386/goreleaser-issue .] env=[GOOS=linux GOARCH=386 GOARM=] target=linux/386
   • running                   cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_darwin_386/goreleaser-issue .] env=[GOOS=darwin GOARCH=386 GOARM=] target=darwin/386
   • new folder                folder=goreleaser-issue_0.0.1_linux_amd64 key=linuxamd64
   • building                  binary=dist/goreleaser-issue_0.0.1_linux_amd64/goreleaser-issue
   • running                   cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_linux_amd64/goreleaser-issue .] env=[GOOS=linux GOARCH=amd64 GOARM=] target=linux/amd64
   • failed                    cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_linux_amd64/goreleaser-issue .] env=[GOOS=linux GOARCH=amd64 GOARM=] error=exit status 2 target=linux/amd64
   • failed                    cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_darwin_386/goreleaser-issue .] env=[GOOS=darwin GOARCH=386 GOARM=] error=exit status 2 target=darwin/386
   • failed                    cmd=[go build -ldflags=-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z -o dist/goreleaser-issue_0.0.1_linux_386/goreleaser-issue .] env=[GOOS=linux GOARCH=386 GOARM=] error=exit status 2 target=linux/386
   ⨯ release failed            error=build failed for linux/amd64:
# github.com/osteele/goreleaser-issue
./main.go:6: undefined: global
```

**Comment by osteele** [comment] 2017-07-12 22:58
I extracted and ran the final command from the debug output, and this elicits the same error:

```bash
$ GOOS=linux GOARCH=386 GOARM= go build -ldflags='-s -w -X main.version=0.0.1 -X main.commit=36c7cd9b8fb4ada38addc1207aae3873de5f4ebe -X main.date=2017-07-12T22:38:48Z' -o dist/goreleaser-issue_0.0.1_linux_386/goreleaser-issue .
# github.com/osteele/goreleaser-issue
./main.go:6: undefined: global
```

So it appears the issue is in cross-compiling to macOS (at least with my toolchain) to Linux, and not necessarily in goreleaser per se except maybe as a documentation issue.

**Comment by osteele** [comment] 2017-07-13 00:57
I get the same error on Travis, only it is able to build Linux but unable to build Darwin: <https://travis-ci.org/osteele/gojekyll/builds/253029404>

```
29.15s$ test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
   • running goreleaser 0.26.1
   • loading config file       file=goreleaser.yml
   • SETTING DEFAULTS 
   • GETTING AND VALIDATING GIT STATE
   • LOADING ENVIRONMENT VARIABLES
   • CHECKING ./DIST  
   • BUILDING BINARIES
   • new folder                folder=gojekyll_0.0.5_Linux_32bit key=linux386
   • building                  binary=dist/gojekyll_0.0.5_Linux_32bit/gojekyll
   • new folder                folder=gojekyll_0.0.5_macOS_64bit key=darwinamd64
   • building                  binary=dist/gojekyll_0.0.5_macOS_64bit/gojekyll
   • new folder                folder=gojekyll_0.0.5_macOS_32bit key=darwin386
   • building                  binary=dist/gojekyll_0.0.5_macOS_32bit/gojekyll
   • new folder                folder=gojekyll_0.0.5_Linux_64bit key=linuxamd64
   • building                  binary=dist/gojekyll_0.0.5_Linux_64bit/gojekyll
   ⨯ release failed            error=build failed for darwin/386:
go build github.com/osteele/liquid/strftime: no buildable Go source files in /home/travis/gopath/src/github.com/osteele/liquid/strftime
# github.com/wellington/go-libsass/libs
../../wellington/go-libsass/libs/sass_number.go:8: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:151: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:153: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:157: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:159: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:164: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:166: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:170: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:175: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:186: undefined: SassNumber
../../wellington/go-libsass/libs/sass_number.go:166: too many errors
```

**Comment by caarlos0** [comment] 2017-08-25 12:47
Yeah, not even this works:

```
~/Code/Go/src/github.com/osteele/goreleaser-issue master 3s
❯ GOOS=linux GOARCH=386 GOARM= go build -o goreleaser-issue .
# github.com/osteele/goreleaser-issue
./main.go:6: undefined: global
```

So, not a goreleaser issue. Closing :)

**Closed by caarlos0** 2017-08-25 12:47 UTC

**Comment by caarlos0** [comment] 2017-08-25 12:48
BTW: this probably happens because when cross-compiling CGO is disabled...

**Comment by jhaynie** [comment] 2017-08-28 20:39
@caarlos0 i apologize for taking so long to respond. i ended up having to rework my build to remove the cross compiled cgo code. it was unrelated to goreleaser and once i did that of course, goreleaser works just fine.

**Comment by caarlos0** [comment] 2017-08-28 20:55
@jhaynie no problem, glad you figured it out :)
