### ISSUE TITLE
Telegram Announcer

### ISSUE THREAD

**Issue by nesty92** [goreleaser/goreleaser#4060] opened 2023-05-31 11:29 UTC
### What happened?

`
posting: 'repo-name v1.16.1 is out! Check it out at https://gitlab.com/user/repo-name/-/releases/v1.16.1'
  ⨯ release failed after 1m14s  error=failed to announce release: 1 error occurred:
	* telegram: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'`

### How can we reproduce this?

Have a repository with a '-' on the name

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.18.2
GitCommit:     ad000694196f30e2cdfe561fd20b20bb85c5258b
GitTreeState:  false
BuildDate:     2023-05-07T02:08:36Z
BuiltBy:       goreleaser
GoVersion:     go1.20.4
Compiler:      gc
ModuleSum:     h1:qeNrKKVOHWEs1+/+a6jwASj7g9yg1R4vfLVlo0Beyro=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2023-05-31 11:57
can you try with main? https://github.com/goreleaser/goreleaser/pull/4036

**Comment by caarlos0** [comment] 2023-06-06 03:22
dupe of https://github.com/goreleaser/goreleaser/issues/4021

**Closed by caarlos0** 2023-06-06 03:22 UTC
Labels: bug, triage
