### ISSUE TITLE
Dropped build targets should break the build (exit -1)

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#2451] opened 2021-09-02 14:41 UTC
```bash
 • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
• DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```

People do not read the release build log -- and even so, then it's too late to fail/stop the release.

**Comment by caarlos0** [comment] 2021-09-02 20:44
we can't do that, the point of the warn was to not fail the build when running on go 1.15, because it would likely not work, and the target was not desired by the user initially (they need to manually ignore it if they want).

now with windows/arm64 is the same thing, it was ignored before, but on go1.17 it is valid.

fwiw these warnings will be removed soon: the macos/aqrm64 one probably in a few weeks and the windows/arm64 ~1 month after go 1.18 is out.

**Comment by caarlos0** [comment] 2021-09-02 23:52
closing as working as intended.

**Closed by caarlos0** 2021-09-02 23:52 UTC
Labels: enhancement
